### ISSUE TITLE
No such file or directory: '\\\\?\\pipe\\discord-ipc-0'

### ISSUE THREAD

**Issue by maxhithere** [Senophyx/Discord-RPC#12]
Full Trace Error:

```
File "C:\Users\right\AppData\Local\Programs\Python\Python311\Lib\site-packages\discordrpc\presence.py", line 192, in _connect
    self._open = open(path, "w+b")
                 ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\right\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\right\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\right\Desktop\D\tool.py", line 2185, in rpc
    rpc = discordrpc.RPC.set_id(appID)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\right\AppData\Local\Programs\Python\Python311\Lib\site-packages\discordrpc\presence.py", line 31, in set_id
    return DiscordWindows(app_id)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\right\AppData\Local\Programs\Python\Python311\Lib\site-packages\discordrpc\presence.py", line 20, in __init__
    self._connect()
  File "C:\Users\right\AppData\Local\Programs\Python\Python311\Lib\site-packages\discordrpc\presence.py", line 194, in _connect
    raise Error("Failed to open {!r}: {}".format(path, e))
discordrpc.exceptions.Error: Failed to open '\\\\?\\pipe\\discord-ipc-0': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-0'
```

This just started happening recently.

**Comment by LyQuid12** [comment]
you use windows right? try different version first, check whether the error is still the same
